`timescale 1ns / 1ps
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE10_LITE_clock(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
wire [3:0] minLeft,minRight;
wire [3:0] secLeft,secRight;
wire [3:0] hourLeft,hourRight;

wire [5:0] second,minute,hour;

wire newDay;

//=======================================================
//  Structural coding
//=======================================================


	split_output sec(second,secLeft,secRight);
	split_output min(minute,minLeft,minRight);
	split_output hr(hour,hourLeft,hourRight);
	
	Clock timer(MAX10_CLK2_50,second,minute,hour,newDay);

	SEG7_LUT	u0	(	HEX0,secRight,1 );
	SEG7_LUT	u1	(	HEX1,secLeft,1 );

	SEG7_LUT	u2	(	HEX2,minRight,0 );
	SEG7_LUT	u3	(	HEX3,minLeft,1 );

	SEG7_LUT	u4	(	HEX4,hourRight,0 );
	SEG7_LUT	u5	(	HEX5,hourLeft,1 );

endmodule
